# Generated by Django 4.2.3 on 2023-07-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='composicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('id', 'tipo', 'marca')},
        ),
    ]
