# Generated by Django 4.2.3 on 2023-07-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_unique_together_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
