# Generated by Django 4.2.3 on 2023-07-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechaEliminacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockInicial',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('tipo', 'marca', 'colorPrincipal', 'coloresSecundarios', 'colorLogo', 'talla', 'mangas')},
        ),
    ]
