# Generated by Django 4.2.3 on 2023-07-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_producto_stockactual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='estado',
            new_name='compra',
        ),
    ]
